services:
  pythonapp:
    image: sundaydied/certi-tester:pythonapp
    ports:
      - '7784:7784'
    command: sh -c "sleep 30s ; python3 ./app.py"
    depends_on:
      - mysql

  mysql:
    image: sundaydied/certi-tester:mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'certi_tsi'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local