name: Docker CI/CD

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Stop and remove all running containers
        run: |
          docker ps -q | xargs -r docker stop
          docker ps -aq | xargs -r docker rm

      - name: Build and tag Docker images
        run: 
          docker-compose up --build -d
          sleep 10 

      - name: Tagging the built images
        run: |
          docker tag certi_tester_deployment-pythonapp sundaydied/certi-tester:pythonapp
          docker tag certi_tester_deployment-mysql sundaydied/certi-tester:mysql

      - name: Push Docker images to Docker Hub
        run: |
          docker push sundaydied/certi-tester:pythonapp
          docker push sundaydied/certi-tester:mysql
      
      - name: Taking the docker container down
        run: | 
           docker-compose down
